select = ["ALL"]
# TCH004 produces false positives
ignore = ["ANN101", "ANN102", "D203", "D211", "D212", "D213", "N802", "UP009", "RET504", "PLR0913", "S101", "INP001", "TCH", "G", "TD", "FA102", "PERF203", "PLR0911", "TRY300"]

exclude = ["docs"]
